# Generated by Django 5.1.1 on 2024-09-25 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltonapp', '0002_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to='images/'),
        ),
    ]
