# Generated by Django 5.1.1 on 2024-10-05 16:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltonapp', '0004_alter_image_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='image',
            old_name='image',
            new_name='nationality',
        ),
        migrations.AddField(
            model_name='image',
            name='age',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='height',
            field=models.CharField(max_length=20, null=True),
        ),
        migrations.AddField(
            model_name='image',
            name='name1',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
