# Generated by Django 5.1.1 on 2024-10-05 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eltonapp', '0005_rename_image_image_nationality_image_age_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='image',
            name='image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
        migrations.AlterField(
            model_name='image',
            name='nationality',
            field=models.CharField(max_length=20, null=True),
        ),
    ]
